DROP TABLE IF EXISTS questions;

CREATE TABLE questions (
  id INTEGER NOT NULL AUTO_INCREMENT DEFAULT NOT NULL,
  body VARCHAR(1000) NOT NULL,
  question_date DATETIME NOT NULL,
  user_id INTEGER NOT NULL,
  helpfulness INTEGER DEFAULT 0,
  reported TINYINT DEFAULT 0,
  product_id INTEGER NOT NULL DEFAULT NOT NULL,
  PRIMARY KEY (question_id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

DROP TABLE IF EXISTS answers;

CREATE TABLE answers (
  id INTEGER NOT NULL AUTO_INCREMENT DEFAULT NOT NULL,
  body VARCHAR(1000) NOT NULL,
  answer_date DATETIME NOT NULL,
  user_id INTEGER NOT NULL,
  helpfulness INTEGER DEFAULT 0,
  question_id INTEGER NOT NULL DEFAULT NOT NULL,
  reported TINYINT DEFAULT 0,
  PRIMARY KEY (id),
  FOREIGN KEY (question_id) REFERENCES questions(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

DROP TABLE IF EXISTS photos;

CREATE TABLE photos (
  id INTEGER NOT NULL AUTO_INCREMENT DEFAULT NOT NULL,
  photo_url VARCHAR(255) NOT NULL,
  answer_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (answer_id) REFERENCES answers(id)
);

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER NOT NULL AUTO_INCREMENT DEFAULT NOT NULL,
  email VARCHAR(100) NOT NULL DEFAULT NOT NULL,
  username VARCHAR(50) NOT NULL DEFAULT NOT NULL,
  PRIMARY KEY (id)
);
